[package]
name = "narrative-director-rs"
version = "0.1.0"
authors = ["Tyler Schmidt <tmschmid@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.14.0"
relm = "^0.22.0"
relm-derive = "^0.22.0"
# Workaround for getting Windows builds to work as well in the meantime.
# If merged from this thread, go back to using normal cpal:
# https://github.com/RustAudio/cpal/pull/504
cpal = { git="https://github.com/JoshuaBatty/cpal", branch="windows_com" }
hound = "^3.4.0"
dirs = "^3.0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"