[package]
name = "narrative-director-rs"
version = "0.1.0"
authors = ["Tyler Schmidt <tmschmid@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "TextGrabber",
    "VideoProcessor",
    "AudioProcessor"
]

[dependencies]
