[package]
name = "narrative-director-rs"
version = "0.1.0"
authors = ["Tyler Schmidt <tmschmid@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "text_grabber",
    "video_processor",
    "audio_processor"
]

[dependencies]
gtk = "^0.9.0"
relm = "^0.21.0"
relm-derive = "^0.21.0"

text_grabber = { path = "text_grabber" }