on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: MacOS CI

jobs:
  check:
    name: Compile and Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Check Code
        run: cargo check
      # NOTE: There is an NSException when running the tests with GUIs:
      #
      # 'Terminating app due to uncaught exception 'NSInternalInconsistencyException',
      # reason: 'nextEventMatchingMask should only be called from the Main Thread!'
      #
      # - name: Run Tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: -- --test-threads=1
