on: [push]

name: Continuous integration

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install gtk3
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgtk-3-dev libasound2-dev
      
      - if: matrix.os == 'macOS-latest'
        run: brew install gtk+3

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-toolchain
            base-devel

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install gtk3
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgtk-3-dev libasound2-dev
      
      - if: matrix.os == 'macOS-latest'
        run: brew install gtk+3

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-toolchain
            base-devel

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Install gtk3
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgtk-3-dev libasound2-dev
      
      - if: matrix.os == 'macOS-latest'
        run: brew install gtk+3

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-toolchain
            base-devel

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
